microsoft/MCW-Cloud-native-applications

- Hands-on lab/HOL step-by-step - Containers and DevOps.md
Added step to commit changes to content-web to add support for environment variables
This fixes issue #32
> Update HOL step-by-step for Environment Variables

- Hands-on lab/HOL step-by-step - Containers and DevOps.md
> fix typo in letsencrypt url

- Hands-on lab/HOL step-by-step - Containers and DevOps.md
- Hands-on lab/HOL unguided - Containers and DevOps.md
I finished going through the exercises and found a couple small typos, clarifications that I found to be helpful about the variance of Azure regions. 😄 I think these small fixes help with clarity.
> fixed 2 typos, added region clarifications 

- Hands-on lab/Before the HOL - Containers and DevOps.md
> Typo: Netwroking

- Hands-on lab/Before the HOL - Containers and DevOps.md
NPM gets installed with NodeJS.
> Remove npm from installations in Task 7 Step 5

- Hands-on lab/HOL step-by-step - Containers and DevOps.md
kubectl apply -f ./api.deployment.yml changed to kubectl apply -f api.deployment.yml
> Exercise 2 Step 2 Task 18 - incorrect path setting

- Hands-on lab/HOL step-by-step - Containers and DevOps.md
Added advice to issue ":set paste" command to ensure proper formatting of pasted code.
> Exercise 2, Task 3: Advice for pasting code

- Whiteboard design session/WDS student guide - Containers and DevOps.md
- Whiteboard design session/WDS trainer guide - Containers and DevOps.md
> Refresh WDS guides

- Hands-on lab/HOL step-by-step - Containers and DevOps - Developer edition.md
Without this update, the static content (CSS, images) won't render.
> fixing ingress path rewrite rule

- Hands-on lab/Before the HOL - Cloud-native applications.md
- Hands-on lab/HOL step-by-step - Cloud-native applications - Developer edition.md
- Hands-on lab/arm/azuredeploy.json
- Hands-on lab/arm/azuredeploy.parameters.json
- Hands-on lab/lab-files/developer/content-web/tsconfig.json
- README.md
AKS cluster upgraded to the latest v1.15 patch and it's ARM template api-version was also updated. Some typos fixed.
Includes content from PR #146 that fixes issue #145, as well as PR #149 that partially fixes issue #147.
> AKS cluster update and content-web fixes

- Hands-on lab/lab-files/infrastructure/content-web/tsconfig.json
Exercise 1 Task 3 - Create and run a Docker application #147
Changing target from es2015 to es5 solves the build issue
> Closes issue #147 - Target fails with es2015

- Hands-on lab/Before the HOL - Cloud-native applications.md
See issue: 
Before the Hands on Lab - Task 6: Azure group deployment is deprecated
> Updating group deployment command

- Hands-on lab/arm/azuredeploy.json
This helps improve stability for access to the kubernetes dashboard.
> Update kubernetesVersion to latest patch release

- Hands-on lab/HOL step-by-step - Cloud-native applications - Developer edition.md
fixed the line format for the yaml file.
> Fix the yaml file.

- Hands-on lab/HOL step-by-step - Cloud-native applications - Developer edition.md
Made a small change with Chris Givens help.
> Indented the yaml tick mark.

- Hands-on lab/HOL step-by-step - Cloud-native applications - Developer edition.md
- Hands-on lab/HOL step-by-step - Cloud-native applications - Infrastructure edition.md
Hello, 
I have transferred some of my changes from my November review to the infrastructure lab.
> Ensuring that the Infrastructure Lab is Updated

- Hands-on lab/HOL step-by-step - Cloud-native applications - Developer edition.md
- Hands-on lab/HOL step-by-step - Cloud-native applications - Infrastructure edition.md
Hello, 
In response to [this issue](https://github.com/microsoft/MCW-Cloud-native-applications/issues/210), I have added the note about the expected insufficient CPU error to both the infrastructure and developer labs.
> Addressing Insufficient CPU Note

- Hands-on lab/HOL step-by-step - Cloud-native applications - Developer edition.md
- Hands-on lab/HOL step-by-step - Cloud-native applications - Infrastructure edition.md
This is no longer accurate with the current state of the lab. Related to issue #215
> Remote note of no data to show

- Hands-on lab/HOL step-by-step - Cloud-native applications - Infrastructure edition.md
I resolved the typo discussed in #224 by updating the infrastructure lab.
> Minor text update

- Hands-on lab/HOL step-by-step - Cloud-native applications - Developer edition.md
This PR contains the following changes
- fix yaml indent error for content-web; related to Issue #217
> Fix Issue 217 error

- Hands-on lab/HOL step-by-step - Cloud-native applications - Developer edition.md
- Hands-on lab/HOL step-by-step - Cloud-native applications - Infrastructure edition.md
This fixes the 404 errors for the content-ingress service, as related to issue #214.
> Fix 404 error for issue #214

- Hands-on lab/arm/azuredeploy.json
> Updating k8s version in ARM template

- Hands-on lab/Before the HOL - Cloud-native applications.md
- Hands-on lab/HOL step-by-step - Cloud-native applications.md
Updates to workshop to resolve #272 and #273
> Adding deployment step to content-web.yml

- Hands-on lab/Before the HOL - Cloud-native applications.md
- Hands-on lab/HOL step-by-step - Cloud-native applications.md
> Resolving #279

- Hands-on lab/HOL step-by-step - Cloud-native applications.md
> Resolving issue #288

- Hands-on lab/HOL step-by-step - Cloud-native applications.md
- Hands-on lab/lab-files/developer/.github/workflows/content-api.yml
- Hands-on lab/lab-files/developer/.github/workflows/content-web.yml
This PR resolves #297. It also contains small fixes that I noted as I worked through the lab.
> Fix for #297

- Hands-on lab/Before the HOL - Cloud-native applications.md
- Hands-on lab/lab-files/developer/scripts/azuredeploy.json
> Adding steps around setting git email and name

- Hands-on lab/Before the HOL - Cloud-native applications.md
- Hands-on lab/lab-files/developer/scripts/create_azure_resources.sh
> Using --scope for az ad sp create

- Hands-on lab/HOL step-by-step - Cloud-native applications.md
Resolves remaining issues in #323
> Changing file extension from yaml to yml
